<a href="https://colab.research.google.com/github/Laru3e/first-repo/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('STEG.csv')
data

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785151,train_Client_121250,2010-12-04,10,405005.0,0,202,6.0,1,200,146,0,0,13669,14015,4,ELEC
785152,train_Client_121250,2009-10-12,10,405005.0,0,202,6.0,1,200,188,0,0,13281,13669,4,ELEC
785153,train_Client_121250,2010-04-08,10,405005.0,0,202,6.0,1,200,193,0,0,14015,14408,4,ELEC
785154,train_Client_121250,2015-02-04,10,405005.0,0,202,8.0,1,249,0,0,0,19317,19566,4,ELEC
785155,train_Client_121250,2009-04-14,10,405005.0,0,202,6.0,1,159,0,0,0,12859,13018,4,ELEC

In [4]:
client_0_bills = data.head(10)
client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [5]:
print(type(client_0_bills))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785156 entries, 0 to 785155
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   client_id             785156 non-null  object
 1   invoice_date          785156 non-null  object
 2   tarif_type            785156 non-null  int64
 3   counter_number        785149 non-null  float64
 4   counter_statue        785156 non-null  int64
 5   counter_code          785156 non-null  int64
 6   reading_remarque      784369 non-null  float64
 7   counter_coefficient   785156 non-null  int64
 8   consommation_level_1  785156 non-null  int64
 9   consommation_level_2  785156 non-null  int64
 10  consommation_level_3  785156 non-null  int64
 11  consommation_level_4  785156 non-null  int64
 12  old_index             785156 non-null  int64
 13  new_index             785156 non-null  int64
 14  months_number         785156 non-null  int64
 15  counter_type          785156 non-null  object
dtypes: float64(2), int64(11), object(3)
memory usage: 95.8+ MB

In [7]:
data.columns

Index(['client_id', 'invoice_date', 'tarif_type', 'counter_number',
       'counter_statue', 'counter_code', 'reading_remarque',
       'counter_coefficient', 'consommation_level_1', 'consommation_level_2',
       'consommation_level_3', 'consommation_level_4', 'old_index',
       'new_index', 'months_number', 'counter_type'],
      dtype='object')

In [11]:
print("shape(rows, columns):", data.shape)

shape(rows, columns): (785156, 16)

In [16]:
categorical_feature = data.select_dtypes(include= ['object', 'category']).columns
print(list(categorical_feature))

['client_id', 'invoice_date', 'counter_type']

In [18]:
print(len(categorical_feature))

3

In [25]:
data.columns

Index(['client_id', 'invoice_date', 'tarif_type', 'counter_number',
       'counter_statue', 'counter_code', 'reading_remarque',
       'counter_coefficient', 'consommation_level_1', 'consommation_level_2',
       'consommation_level_3', 'consommation_level_4', 'old_index',
       'new_index', 'months_number', 'counter_type'],
      dtype='object')

In [29]:
print("memory usage=", round(data.memory_usage(deep=True).sum()))

memory usage= 222651915

In [34]:
missen_value = data.isnull().sum()
missen_value

client_id                 0
invoice_date              0
tarif_type                0
counter_number            7
counter_statue            0
counter_code              0
reading_remarque        787
counter_coefficient       0
consommation_level_1      0
consommation_level_2      0
consommation_level_3      0
consommation_level_4      0
old_index                 0
new_index                 0
months_number             0
counter_type              0
dtype: int64

In [39]:
x = data.columns[data.isnull().any()]
x

Index(['counter_number', 'reading_remarque'], dtype='object')

In [53]:
##missing values

for col in data.columns:
  if data[col].isnull().sum() > 0:
    if data[col].dtype in ['float64', 'int64']:
      data[col].fillna(data[col].median(), inplace= True)
    else:
      data[col].fillna(data[col].mode()[0], inplace= True)
print('missing values after handling:', data.isnull().sum())

missing values after handling: client_id               0
invoice_date            0
tarif_type              0
counter_number          0
counter_statue          0
counter_code            0
reading_remarque        0
counter_coefficient     0
consommation_level_1    0
consommation_level_2    0
consommation_level_3    0
consommation_level_4    0
old_index               0
new_index               0
months_number           0
counter_type            0
dtype: int64

/tmp/ipykernel_5642/1129246390.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].median(), inplace= True)

mode was used for categorical data while median was used for continous or numeric data

In [55]:
data.describe()

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,785156.000000,7.851560e+05,785156.000000,785156.000000,785156.000000,785156.000000,785156.000000,785156.000000,785156.000000,785156.000000,7.851560e+05,7.851560e+05,785156.000000
mean,20.130974,1.184475e+11,0.042211,172.276689,7.320358,1.000316,409.125733,108.516025,20.711943,53.469467,1.762505e+04,1.819783e+04,35.119465
std,13.475638,1.627848e+12,0.374716,133.537298,1.360239,0.095986,575.516993,1283.258204,174.702932,1005.312203,4.021824e+04,4.080680e+04,2087.833123
min,8.000000,0.000000e+00,0.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,1.000000
25%,11.000000,1.225030e+05,0.000000,5.000000,6.000000,1.000000,79.000000,0.000000,0.000000,0.000000,1.780000e+03,2.049000e+03,4.000000
50%,11.000000,4.928500e+05,0.000000,203.000000,8.000000,1.000000,272.000000,0.000000,0.000000,0.000000,7.664000e+03,8.168000e+03,4.000000
75%,40.000000,1.111436e+06,0.000000,207.000000,9.000000,1.000000,601.000000,0.000000,0.000000,0.000000,2.175200e+04,2.244500e+04,4.000000
max,45.000000,2.738110e+13,5.000000,600.000000,9.000000,50.000000,93385.000000,819886.000000,45360.000000,343568.000000,2.800280e+06,2.870972e+06,285398.000000

In [58]:
client0_method1 = data[data['client_id'] == 'train_Client_0']
client0_method1

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,2008-11-25,11,1335667.0,0,203,6.0,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,2012-07-23,11,1335667.0,0,203,6.0,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,2012-11-29,11,1335667.0,0,203,6.0,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,2013-07-22,11,1335667.0,0,203,8.0,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,2014-07-18,11,1335667.0,0,203,8.0,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,2014-11-24,11,1335667.0,0,203,8.0,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,2015-11-18,11,1335667.0,0,207,9.0,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,2012-03-27,11,1335667.0,0,203,8.0,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,2011-03-30,11,1335667.0,0,203,6.0,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2013-02-12,11,1335667.0,0,203,8.0,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,2010-07-22,11,1335667.0,0,203,6.0,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,2010-11-24,11,1335667.0,0,203,6.0,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,2005-10-17,11,1335667.0,0,203,6.0,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2006-02-24,11,1335667.0,0,203,6.0,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,2006-06-23,11,1335667.0,0,203,6.0,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,2006-10-18,11,1335667.0,0,203,6.0,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,2007-06-27,11,1335667.0,0,203,6.0,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,2007-10-25,11,1335667.0,0,203,6.0,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2007-02-26,11,1335667.0,0,203,6.0,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,2008-07-28,11,1335667.0,0,203,6.0,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,2009-01-04,11,1335667.0,0,203,6.0,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,2009-07-27,11,1335667.0,0,203,6.0,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,2009-11-24,11,1335667.0,0,203,6.0,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,2010-03-29,11,1335667.0,0,203,6.0,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,2008-01-04,11,1335667.0,0,203,6.0,1,277,0,0,0,4969,5246,4,ELEC

In [59]:
client0_method2 = data.loc[data['client_id'] == 'train_Client_0']
client0_method2

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,2008-11-25,11,1335667.0,0,203,6.0,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,2012-07-23,11,1335667.0,0,203,6.0,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,2012-11-29,11,1335667.0,0,203,6.0,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,2013-07-22,11,1335667.0,0,203,8.0,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,2014-07-18,11,1335667.0,0,203,8.0,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,2014-11-24,11,1335667.0,0,203,8.0,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,2015-11-18,11,1335667.0,0,207,9.0,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,2012-03-27,11,1335667.0,0,203,8.0,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,2011-03-30,11,1335667.0,0,203,6.0,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2013-02-12,11,1335667.0,0,203,8.0,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,2010-07-22,11,1335667.0,0,203,6.0,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,2010-11-24,11,1335667.0,0,203,6.0,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,2005-10-17,11,1335667.0,0,203,6.0,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2006-02-24,11,1335667.0,0,203,6.0,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,2006-06-23,11,1335667.0,0,203,6.0,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,2006-10-18,11,1335667.0,0,203,6.0,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,2007-06-27,11,1335667.0,0,203,6.0,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,2007-10-25,11,1335667.0,0,203,6.0,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2007-02-26,11,1335667.0,0,203,6.0,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,2008-07-28,11,1335667.0,0,203,6.0,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,2009-01-04,11,1335667.0,0,203,6.0,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,2009-07-27,11,1335667.0,0,203,6.0,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,2009-11-24,11,1335667.0,0,203,6.0,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,2010-03-29,11,1335667.0,0,203,6.0,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,2008-01-04,11,1335667.0,0,203,6.0,1,277,0,0,0,4969,5246,4,ELEC

In [62]:
encoder = LabelEncoder()
data['encoded'] = encoder.fit_transform(data['counter_type'])
data['encoded'].unique()

array([0, 1])

In [63]:
data['counter_type'].unique()

array(['ELEC', 'GAZ'], dtype=object)

In [ ]:
data = data.drop(data['counter_type'])